version: "3.8"
services:
  user-service:
    image: user-service:latest
    container_name: "user-service"
    ports:
      - "9001:9001"

  contact-service:
    image: contact-service:latest
    container_name: "contact-service"
    ports:
      - "9002:9002"

  api-gateway:
    image: api-gateway:latest
    container_name: "api-gateway"
    ports:
      - "8999:8999"

  eureka-server:
    image: eureka-server:latest
    container_name: "eureka-server"
    ports:
      - "8761:8761"
