spring:
  batch:
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/userdatabase
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      javax:
        persistence:
          validation:
            mode: none
